### PR TITLE
call all methods that "get details" same method call

### PR DESCRIPTION
**Pull request by kennethkoontz**
@jordanskole this will affect your script. But we should name them the same.

### CODE REVIEW

**Comment by jordanskole** [comment]
:+1:

**Comment by kennethkoontz** [comment]
@jordanskole heads up

**Comment by kennethkoontz** [comment]
@jordanskole uploaded to pypi

```
pip install --upgrade benchmark-places
```

**Comment by jordanskole** [comment]
:palm_tree:

**Pull request merged**
